# Generated by Django 5.0.6 on 2024-07-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Surname')),
            ],
            options={
                'verbose_name': 'User of the Bot',
                'verbose_name_plural': 'Users of the Bot',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name of the Channel')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='User of the Bot')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('creator', models.CharField(blank=True, max_length=150, null=True, verbose_name='creator')),
                ('expire_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='expire_date')),
                ('member_limit', models.CharField(blank=True, max_length=150, null=True, verbose_name='member_limit')),
                ('is_primary', models.CharField(blank=True, max_length=150, null=True, verbose_name='is_primary')),
                ('pending_join_request_count', models.CharField(blank=True, max_length=150, null=True, verbose_name='pending_join_request_count')),
                ('telegram_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchannel', verbose_name='Telegram channel')),
            ],
            options={
                'verbose_name': 'Invitation link',
                'verbose_name_plural': 'Invitation links',
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Surname')),
                ('subscribed', models.BooleanField(default=False, verbose_name='Subscribed')),
                ('datetime_subscribe', models.DateTimeField(blank=True, null=True, verbose_name='Subscription time')),
                ('datetime_unsubscribe', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscription time')),
                ('invite_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchannel', verbose_name='Invitation Link')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
