# Generated by Django 5.0.6 on 2024-07-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_telegramchannel_bot_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='creates_join_request',
            field=models.BooleanField(default=False, verbose_name='Request for joining'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='is_revoked',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is revoked'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='public_link',
            field=models.BooleanField(default=False, verbose_name='Public link'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='is_primary',
            field=models.BooleanField(blank=True, null=True, verbose_name='is_primary'),
        ),
    ]
